[package]
name = "seeds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flamegraph = "0.6.4"
futures = "0.3.29"
rayon = "1.8.0"
